#pragma once
#include"Lexeme.h"
enum Err{ERR_FILE,ERR_INPUT_ARGUMENT_NUM,ERR_LEX,ERR_SYNTAX,ERR_SYM_RETRACT,ERR_TOKEN_FLOW,
	ERR_IDEN_DECLARED,ERR_IDEN_NOT_DECLARED,ERR_REQUIRE_ARRAY,
	ERR_CONST,ERR_TAB_FLOW,ERR_ARRAY_FLOW,
	ERR_REQUIRE_FUNC,ERR_PARAMTYPE_NOT_MATCH,ERR_PARAMNUM_LESS,ERR_PARAMNUM_MORE,
	ERR_REQUIRE_VAR,ERR_REQUIRE_RET,ERR_CASE_MATCH,ERR_INTOCHAR,
	ERR_MAIN_RET_TYPE,ERR_MAIN_PARAM, ERR_PARAM_FLOW,
	ERR_DIV_ZERO,ERR_INSTR_NOT_DEFINE, ERR_QCODE_NOT_DEFINE
};
void error(int err );
void error(int err, int detail);
